name: CICD
on:
  push:
    branches: [aws]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Image
        env:
          TAG: ${{ github.sha }}
        run: |
          docker build -t tienmanh/flow-pilot-fe:latest -t tienmanh/flow-pilot-fe:${TAG::7} .
          docker push tienmanh/flow-pilot-fe:latest
          docker push tienmanh/flow-pilot-fe:${TAG::7}

  deploy:
    needs: build
    runs-on: [self-hosted, Linux, X64]  # EC2 runner
    steps:
      - name: Pull image
        run: sudo docker pull tienmanh/flow-pilot-fe:latest

      - name: Stop & remove old
        run: sudo docker rm -f flow-pilot-fe-container || true

      - name: Run container (host 6868 -> container 80)
        run: |
          sudo docker run -d --name flow-pilot-fe-container \
            -p 6868:6868 \
            --restart unless-stopped \
            tienmanh/flow-pilot-fe:latest

      - name: Clean dangling images (optional)
        run: sudo docker image prune -f
