name: CICD

on:
  push:
    branches:
      - aws

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t tienmanh/flow-pilot-fe .

      - name: Push Docker Image
        run: docker push tienmanh/flow-pilot-fe:latest
  deploy:
    needs: build
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Pull image from Docker Hub
        run: sudo docker pull tienmanh/flow-pilot-fe:latest

      - name: Delete Old Container
        run: sudo docker rm -f flow-pilot-fe-container || true

      - name: Run docker container
        run: sudo docker run -d -p 6868:6868 --name flow-pilot-fe-container tienmanh/flow-pilot-fe:latest